Add an integration test for validating all the golden tables
This currently fails because a parquet file's schema is not delta compatible
somehow:

thread 'test_all_tables' panicked at 'Failed to convert the schema for creating the table: SchemaError("Invalid data type for Delta Lake: Timestamp(Nanosecond, None)")', /usr/home/tyler/source/github/buoyant-data/oxbow/src/lib.rs:118:10

I have a hunch that this might be similar to delta-io/delta-rs#1286